; Exercise 9
; Here we are contrasting the processes generated by two recursive procedures.

(define (+ a b)
	(if (= a 0)
		b
		(inc (+ (dec a) b))))

; The process generated by the above procedure is recursive.
;
; The evolution of this process as demonstrated by the substitution model:
; (+ 4 5)
; (inc (+ 3 5))
; (inc (inc (+ 2 5)))
; (inc (inc (inc (+ 1 5))))
; (inc (inc (inc (inc (+ 0 5)))))
; (inc (inc (inc (inc 5))))
; (inc (inc (inc 6)))
; (inc (inc 7))
; (inc 8)
; 9
;
		
		
(define (+ a b)
	(if (= a 0)
		b
		(+ (dec a) (inc b))))
		
; The process generated by the above procedure is iterative.	
;
; The evolution of this process as demonstrated by the substitution model:
; (+ 4 5)
; (+ 3 6)
; (+ 2 7)
; (+ 1 8)
; (+ 0 9)
; 9
		
		
; Auxiliary procedures
(define (inc n)
	(+ n 1))
	
(define (dec n)
	(- n 1))